config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :action_points, except: [:show, :destroy]
  resources :attachments, except: [:show, :destroy]
  resources :dayoffs do
    get :employees, on: :collection
  end
  resources :events, only: :index
  resources :expenses
  resources :notes, except: [:show, :destroy]
  resources :people do
    get :autocomplete_employee_name, on: :collection
    get :autocomplete_person_name, on: :collection
  end
  resources :project_notes, except: [:show, :destroy]
  resources :projects, except: [:destroy] do
    get :autocomplete_project_name, on: :collection
  end
  resources :reports, only: :index do
    collection do
      # get :by_status
      # get :by_technology
      get :current_employees_table
      get :contractors_table
      get :employees_by_birthday_month
      get :employees_by_last_one_on_one_meeting_date
      get :employees_without_performance_review
      get :employees_expenses
      get :employees_history
      get :employees_simple
      get :employees_without_nda_signed
      get :funnel
      get :historical_data
      get :people_with_similar_name
      get :searches
    end
  end
  resources :search, only: :index
  resources :tags, only: :index
  resources :users, except: :destroy
  resources :vacancies, except: :destroy

  root 'home#index'
end

app/models/person.rb
class Person < ActiveRecord::Base
  include ChangesTracker

  acts_as_taggable_on :tags
  attachment :photo

  PRIMARY_TECHS = %w(
    Android
    C/C++/Go
    DBA
    DevOps
    Frontend
    Fullstack
    HR
    iOS
    Java
    Manager
    ML
    NET
    PHP
    PM
    Python
    Ruby
    Sales
    Salesforce
    Scala
    QA/BA
    UI/UX
    Wordpress
    Xamarin
  )
  ENGLISH_LEVELS = %w(
    Beginner/Elementary
    Pre-Intermediate
    Intermediate
    Upper-Intermediate
    Advanced
  )
  CURRENT_EMPLOYEE_STATUSES = %w(Hired Contractor)
  EMPLOYEE_STATUSES = ['Hired', 'Past employee', 'Contractor', 'Past contractor']
  SALARY_TYPES = %w(Monthly Hourly)

  belongs_to :updated_by, class_name: 'User'
  has_many :action_points
  has_many :attachments
  has_many :dayoffs
  has_many :expenses
  has_many :notes

  before_validation :cleanup
  before_save :strip_values

  validates :name, presence: true
  validates :salary_type, inclusion: { in: SALARY_TYPES }, allow_blank: true
  validates :primary_tech, inclusion: { in: PRIMARY_TECHS }
  validates :vacation_override, numericality: { only_integer: true }, allow_blank: true
  validates :email, :phone, :skype, :linkedin, :github, uniqueness: { case_sensitive: false, conditions: -> { not_deleted } }, allow_blank: true
  validates :name, format: { with: /\A[a-zA-Z\d\s\-\'\(\)]+\z/, message: 'invalid symbols. Only A-Z, digits, braces, quote and space allowed' }, allow_blank: true
  validates :phone, format: { with: /\A[\s\+\,\d]+\z/ }, allow_blank: true
  validates :email, format: { with: /\A[0-9a-z\@\.\_\-\'\+]+\z/ }, allow_blank: true
  validates :skype, format: { with: /\A[0-9a-z\.\:\_\-]+\z/ }, allow_blank: true
  validates :start_date, presence: { message: 'should be present for current employee' }, if: ->(p) { p.status.in?(EMPLOYEE_STATUSES) && !p.new_record? }
  validates :email, presence: { message: 'should be present for current employee' }, if: ->(p) { p.status.in?(CURRENT_EMPLOYEE_STATUSES) && p.start_date.present? && p.start_date <= Time.zone.now }
  validate :finish_date_greater_or_equal_start_date

  scope :not_deleted, ->() { where(is_deleted: false) }
  scope :employee, ->() { where(status: EMPLOYEE_STATUSES).order(:status) }
  scope :current_employee, ->() { where(status: 'Hired').order(:name) }

  def linkedin_value
    if self.linkedin.start_with?('https://')
      self.linkedin
    elsif self.linkedin.start_with?('http://')
      self.linkedin.gsub('http://', 'https://')
    else
      "https://#{self.linkedin}"
    end
  end

  def github_value
    if self.github.start_with?('https://')
      self.github
    elsif self.github.start_with?('http://')
      self.github.gsub('http://', 'https://')
    else
      "https://#{self.github}"
    end
  end

private

  def cleanup
    self.email = email.to_s.downcase
    self.skype = skype.to_s.downcase
  end

  def strip_values
    self.phone = self.phone.to_s.strip
    self.current_position = self.current_position.to_s.strip
    self.email = self.email.to_s.strip
    self.skype = self.skype.to_s.strip
    self.linkedin = self.linkedin.to_s.strip.split('?').first.to_s
    self.github = self.github.to_s.strip.split('?').first.to_s
    self.name = self.name.to_s.strip
  end

  def finish_date_greater_or_equal_start_date
    return if start_date.blank? || finish_date.blank? || start_date <= finish_date
    errors.add(:start_date, 'should be earlier than finish_date')
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  load_and_authorize_resource
  autocomplete :person, :name, full: true, scopes: [:not_deleted]
  autocomplete :employee, :name, class_name: 'Person', full: true, scopes: [:not_deleted, :employee]

  def index
    @q = Person.not_deleted.accessible_by(current_ability).ransack(params[:q])
    @q.sorts = 'updated_at desc' if @q.sorts.empty?
    @people = @q.result(distinct: true)

    if params.dig(:q, :by_tag_including)
      @people = @people.tagged_with(params[:q][:by_tag_including], any: true)
    end
    if params.dig(:q, :by_tag_excluding)
      @people = @people.tagged_with(params[:q][:by_tag_excluding], exclude: true)
    end

    @count = @people.count
    @people = @people.offset(params.dig(:page, :offset)) if params.dig(:page, :offset).present?
    @people = @people.limit((params.dig(:page, :limit) || ENV['ITEMS_PER_PAGE']).to_i)

    @people = @people.includes(:attachments, :action_points, :updated_by, :taggings, notes: [:updated_by])

    @tags = Person.not_deleted.accessible_by(current_ability).tag_counts_on(:tags)
      .sort { |t1, t2| t2.taggings_count <=> t1.taggings_count }

    respond_to do |f|
      f.partial { render partial: 'table' }
      f.json { render json: @people }
      f.html
    end
  end

  def show
    @person.notes = @person.notes.includes(:updated_by)
    @action_point = ActionPoint.new(person: @person)
    @attachment = Attachment.new(person: @person)
    @dayoff = Dayoff.new(person: @person)
    @expense = Expense.new(person: @person)
    @note = Note.new(person: @person)
  end

  def new
  end

  def create
    @person = Person.new(person_params.merge!(updated_by: current_user))
    if @person.save
      @person.update!(photo: person_photo_params[:photo]) if person_photo_params[:photo].present?
      log_event(entity: @person, action: 'created')
      redirect_to (session[:return_to] && session[:return_to][request.params[:controller]]) || people_path, flash: { success: 'Person created' }
    else
      flash.now[:error] = 'Person was not created'
      render :new
    end
  end

  def edit
  end

  def update
    if @person.update(person_params.merge!(updated_by: current_user))
      @person.update!(photo: person_photo_params[:photo]) if person_photo_params[:photo].present?
      log_event(entity: @person, action: 'updated')
      redirect_to person_path(@person)
      # redirect_to (session[:return_to] && session[:return_to][request.params[:controller]]) || people_path, flash: { success: 'Person updated' }
    else
      flash.now[:error] = 'Person was not updated'
      render :edit
    end
  end

  def destroy
    @person.update_column(:is_deleted, true)
    log_event(entity: @person, action: 'deleted')
    redirect_to people_path, flash: { success: 'Person was deleted but can be restored manually' }
  end

private

  def person_photo_params
    params.require(:person).permit(:photo)
  end

  def person_params
    params.require(:person).permit(:name, :city, :phone, :skype, :linkedin, :email, :start_date,
      :primary_tech, :current_position, :english, :day_of_birth, :status, :expected_salary, :source,
      :vacation_override, :skills, :finish_date, :signed_nda, :salary_type, :employee_id,
      :last_one_on_one_meeting_at, :last_performance_review_at, :next_performance_review_at,
      :github,
      tag_list: [])
  end
end

app/helpers/people_helper.rb
module PeopleHelper
  def hr_status_updates(person_id)
    r = Event.where(action: %w(person.updated person.created), entity_id: person_id, entity_type: 'Person')
         .order(created_at: :desc).map do |event|
      next if event.params['status'].blank?
      [event.params['status'], event.created_at]
    end.compact
  end
end

app/views/people/_show_candidate.slim
- if @person.primary_tech.present?
  p
    | Primary tech:&nbsp;
    strong = @person.primary_tech

p
  | Status:&nbsp;
  span style="background-color: #{PERSON_STATUS_COLORS[@person.status]};"
    = @person.status.presence || 'n/a'

p
  | Status history:&nbsp;
  br
  - hr_status_updates(@person.id).each do |item|
    = item.last.strftime(t(:day))
    |&nbsp;
    span style="background-color: #{PERSON_STATUS_COLORS[item.first&.last]};"
      = item.first&.last.presence || 'n/a'
    br

- if @person.source.present?
  p
    | Hiring Source:&nbsp;
    strong = with_newlines(@person.source)

- if @person.skills.present?
  p
    | Skills:&nbsp;
    strong = with_newlines(@person.skills)

- if @person.skype.present?
  p
    | Skype:&nbsp;
    strong
      a href="skype:#{@person.skype}" #{@person.skype}

- if @person.linkedin.present?
  p
    | LinkedIn:&nbsp;
    strong
      a target="_blank" href="#{@person.linkedin_value}" View

- if @person.github.present?
  p
    | Github:&nbsp;
    strong
      a target="_blank" href="#{@person.github_value}" View

- if @person.city.present?
  p
    | City:&nbsp;
    strong = @person.city.presence

- vacancies = Vacancy.where(tag: @person.tag_list).order(id: :desc)
- if vacancies.present?
  p
    | Vacancies:&nbsp;
    - vacancies.each do |vacancy|
      = link_to "#{vacancy.project}, #{vacancy.role}", vacancy_path(vacancy)
      | &nbsp;(
      = vacancy.status
      | )&nbsp;

- unless @person.tag_list.empty?
  p
    | Tags:&nbsp;
    - @person.tag_list.each do |tag|
      = link_to tag, people_path(q: {by_tag_including: tag})
      | &nbsp;

- if @person.english.present?
  p
    | English:&nbsp;
    strong
      = @person.english

- if current_user.has_access_to_finances? && @person.expected_salary.present?
  p
    | Expected salary:&nbsp;
    strong = @person.expected_salary

- if @person.email.present?
  p
    | Email:&nbsp;
    - if @person.status.in?(Person::EMPLOYEE_STATUSES) && !ENV['COMPANY_EMAIL_MASK'].in?(@person.email)
      span style="color: red"
        = @person.email
    - else
      strong
        = @person.email

- if @person.phone.present?
  p
    | Phone:&nbsp;
    strong
      a href="tel:#{@person.phone}" #{@person.phone}

h3
  | Latest notes &nbsp;
  = link_to 'Add', new_note_path(note: {person_id: @person.id}), class: 'btn btn-default'

- @person.notes.accessible_by(current_ability).order(updated_at: :desc).each do |note|
  p
    = note.created_at.strftime(t(:datetime_full)).gsub('00:00, ', '')
    | &nbsp;(#{note.updated_by&.email&.split('@')&.first || '?'})&nbsp;

    - if !note.type.in?(Note::FINANCE_TYPES) || (note.type.in?(Note::FINANCE_TYPES) && current_user.has_access_to_finances?)
      a href="#{edit_note_path(note)}" #{note.type}
      br
      ' #{with_newlines(note.value)}
    - else
      = "Content of this note is not available (#{note.type})"
  br

h3
  | Actions &nbsp;
  = link_to 'Add', new_action_point_path(action_point: {person_id: @person.id}), class: 'btn btn-default'

- @person.action_points.order(is_completed: :asc, perform_on: :desc).each do |action|
  p
    a href="#{edit_action_point_path(action)}" #{action.perform_on.strftime(t(:datetime_full)).gsub('00:00, ', '')}
    | &nbsp; #{action.is_completed? ? 'completed' : ''}
    br
    = with_newlines(action.value)

h3
  | Attachments &nbsp;
  = link_to 'Add', new_attachment_path(attachment: {person_id: @person.id}), class: 'btn btn-default'

- @person.attachments.order(created_at: :desc).each do |attachment|
  - if !(attachment.name.presence || attachment.file_filename).include?('offer') || ((attachment.name.presence || attachment.file_filename).include?('offer') && current_user.has_access_to_finances?)
    p
      = link_to (attachment.name.present? ? attachment.name : attachment.file_filename), Refile.attachment_url(attachment, :file)
      |&nbsp;(
      = attachment.created_at.strftime(t(:day)).gsub('00:00, ', '')
      |)
      - if attachment.description.present?
        br = with_newlines(attachment.description)
    br

app/views/people/_show_employee.slim
- if @person.photo.present?
  p
    img src="#{Refile.attachment_url(@person, :photo, :fit, 200, 200, format: 'jpg')}"

- if @person.skills.present?
  p
    | Skills:&nbsp;
    strong = with_newlines(@person.skills)

- if @person.primary_tech.present?
  p
    | Primary tech:&nbsp;
    strong = @person.primary_tech

- if @person.current_position.present?
  p
    | Current Position:&nbsp;
    strong = @person.current_position

p
  | Current Status:&nbsp;
  span style="background-color: #{PERSON_STATUS_COLORS[@person.status]};"
    = @person.status.presence || 'n/a'

p
  | Status history:&nbsp;
  br
  - hr_status_updates(@person.id).each do |item|
    = item.last.strftime(t(:day))
    |&nbsp;
    span style="background-color: #{PERSON_STATUS_COLORS[item.first&.last]};"
      = item.first&.last.presence || 'n/a'
    br

- if @person.skype.present?
  p
    | Skype:&nbsp;
    strong
      a href="skype:#{@person.skype}" #{@person.skype}

- if @person.linkedin.present?
  p
    | LinkedIn:&nbsp;
    strong
      a target="_blank" href="#{@person.linkedin_value}" View

- if @person.github.present?
  p
    | Github:&nbsp;
    strong
      a target="_blank" href="#{@person.github_value}" View

- if @person.city.present?
  p
    | City:&nbsp;
    strong = @person.city.presence

- vacancies = Vacancy.where(tag: @person.tag_list).order(id: :desc)
- if vacancies.present?
  p
    | Vacancies:&nbsp;
    - vacancies.each do |vacancy|
      = link_to "#{vacancy.project}, #{vacancy.role}", vacancy_path(vacancy)
      | &nbsp;(
      = vacancy.status
      | )&nbsp;

- unless @person.tag_list.empty?
  p
    | Tags:&nbsp;
    - @person.tag_list.each do |tag|
      = link_to tag, people_path(q: {by_tag_including: tag})
      | &nbsp;

- if @person.english.present?
  p
    | English:&nbsp;
    strong = @person.english

- if current_user.has_access_to_finances? && @person.expected_salary.present?
  p
    | Expected salary:&nbsp;
    strong = @person.expected_salary

- if @person.email.present?
  p
    | Email:&nbsp;
    - if @person.status.in?(Person::EMPLOYEE_STATUSES) && !ENV['COMPANY_EMAIL_MASK'].in?(@person.email)
      span style="color: red"
        = @person.email
    - else
      strong = @person.email

- if @person.phone.present?
  p
    | Phone:&nbsp;
    strong
      a href="tel:#{@person.phone}" #{@person.phone}

- if @person.start_date.present?
  p
    | Employment Start Date:&nbsp;
    strong = @person.start_date.strftime(t(:datetime_full)).gsub('00:00, ', '')

p
  - if @person.signed_nda?
    | Signed Documents
  - else
    span style="color: red"
      | Documents are not signed!

- if @person.employee_id.present?
  p
    | Employee ID:&nbsp;
    strong = @person.employee_id

- if @person.salary_type.present?
  p
    | Salary type:&nbsp;
    strong = @person.salary_type

- if @person.last_one_on_one_meeting_at.present?
  p
    | Last 1-1 meeting with management:&nbsp;
    strong = @person.last_one_on_one_meeting_at.strftime(t(:datetime_full)).gsub('00:00, ', '')

- if @person.last_performance_review_at.present?
  p
    | Last performance review:&nbsp;
    strong = @person.last_performance_review_at.strftime(t(:datetime_full)).gsub('00:00, ', '')

- if @person.next_performance_review_at.present?
  p
    | Next performance review planned:&nbsp;
    strong = @person.next_performance_review_at.strftime(t(:datetime_full)).gsub('00:00, ', '')

- if @person.finish_date.present?
  p
    | Employment Finish Date:&nbsp;
    strong = @person.finish_date.strftime(t(:datetime_full)).gsub('00:00, ', '')

- if @person.day_of_birth.present?
  p
    | Date of birth:&nbsp;
    strong = @person.day_of_birth.strftime(t(:datetime_full)).gsub('00:00, ', '')

- if @person.source.present?
  p
    | Hiring Source:&nbsp;
    strong = @person.source

- if @person.vacation_override.to_i > 0
  p
    | Override vacation days per year:&nbsp;
    strong #{@person.vacation_override}

h3
  | Days off &nbsp;
  = link_to 'Add', new_dayoff_path(dayoff: {person_id: @person.id}), class: 'btn btn-default'
table.table.pretty-table
  tr
    th
      | Period
    th
      | Data
  - vacation_stats_per_year(@person.id).reverse_each.to_h.each_pair do |index, item|
    tr
      td
        = "#{item['period']}, #{(item['year'] + 1).ordinalize} year"
      td
        | Yearly vacation days added: #{item['yearly_vacation_days_assigned']}
        br
        | Total period vacation days: #{item['total_vacation_days']}
        br
        | Used vacation days: #{item['used_vacation']}
        br
        | Overtime days: #{item['overtime_days']}
        br
        | Sick leave days: #{item['sick_leave_days']}
        br
        | Unpaid days off: #{item['unpaid_days_off']}
        br
        | Paid days off: #{item['paid_days_off']}
        br
        | Working day shifts: #{item['working_days_shifts']}
        br
          strong
            | Remaining vacation: #{item['remaining_vacation']}
        | Days will burn: #{item['burn_days']}
        br
        | Days will be transferred: #{item['transfer_days']}

br
- @person.dayoffs.order(start_on: :desc).each do |dayoff|
  p
    a href="#{dayoff_path(dayoff)}" #{dayoff.type}
    | &nbsp;
    | #{"#{pluralize(dayoff.days, 'day')} from #{dayoff.start_on&.to_formatted_s(:rfc822)} to #{dayoff.end_on&.to_formatted_s(:rfc822)}"}
    | &nbsp;&nbsp;
    a href="#{edit_dayoff_path(dayoff)}"
      i.fa.fa-pencil
    | &nbsp;&nbsp;
    a href="#{dayoff_path(dayoff)}" data-method="delete" data-confirm="Are you sure ?"
      i.fa.fa-times
    br
    = with_newlines(dayoff.notes)

h3
  | Expenses &nbsp;
  = link_to 'Add', new_expense_path(expense: {person_id: @person.id}), class: 'btn btn-default'

| Total: $#{@person.expenses.sum(:amount)}
br
- @person.expenses.order(recorded_on: :desc).each do |expense|
  p
    a href="#{expense_path(expense)}" #{expense.type}
    | &nbsp;
    | $#{expense.amount} for #{expense.recorded_on&.to_formatted_s(:rfc822)}
    | &nbsp;&nbsp;
    a href="#{edit_expense_path(expense)}"
      i.fa.fa-pencil
    | &nbsp;&nbsp;
    a href="#{expense_path(expense)}" data-method="delete" data-confirm="Are you sure ?"
      i.fa.fa-times
    br
    = with_newlines(expense.notes)

h3
  | Latest notes &nbsp;
  = link_to 'Add', new_note_path(note: {person_id: @person.id}), class: 'btn btn-default'

- @person.notes.accessible_by(current_ability).order(updated_at: :desc).each do |note|
  p
    = note.created_at.strftime(t(:datetime_full)).gsub('00:00, ', '')
    | &nbsp;(#{note.updated_by&.email&.split('@')&.first || '?'})&nbsp;

    - if !note.type.in?(Note::FINANCE_TYPES) || (note.type.in?(Note::FINANCE_TYPES) && current_user.has_access_to_finances?)
      a href="#{edit_note_path(note)}" #{note.type}
      br
      ' #{with_newlines(note.value)}
    - else
      = "Content of this note is not available (#{note.type})"
  br

h3
  | Actions &nbsp;
  = link_to 'Add', new_action_point_path(action_point: {person_id: @person.id}), class: 'btn btn-default'

- @person.action_points.order(is_completed: :asc, perform_on: :desc).each do |action|
  p
    a href="#{edit_action_point_path(action)}" #{action.perform_on.strftime(t(:datetime_full)).gsub('00:00, ', '')}
    | &nbsp; #{action.is_completed? ? 'completed' : ''}
    br
    = with_newlines(action.value)

h3
  | Attachments &nbsp;
  = link_to 'Add', new_attachment_path(attachment: {person_id: @person.id}), class: 'btn btn-default'

- @person.attachments.order(created_at: :desc).each do |attachment|
  - if !(attachment.name.presence || attachment.file_filename).include?('offer') || ((attachment.name.presence || attachment.file_filename).include?('offer') && current_user.has_access_to_finances?)
    p
      = link_to (attachment.name.present? ? attachment.name : attachment.file_filename), Refile.attachment_url(attachment, :file)
      |&nbsp;(
      = attachment.created_at.strftime(t(:day)).gsub('00:00, ', '')
      |)
      - if attachment.description.present?
        br
        = with_newlines(attachment.description).as_json()
    br

app/views/people/_table.slim
- if @people.empty?
  span class='js-page-last'

- @people.each_with_index do |record, index|
  tr class=('js-page-last' if (index == @people.size - 1) && last_page?(@people))
    td
      strong
        = link_to record.name.titleize, person_path(record)
      | &nbsp;
      a href="#{edit_person_path(record)}"
        i.fa.fa-pencil
      - if record.linkedin.blank? && record.attachments.empty?
        br
        a.btn.btn-xs.btn-danger href="#{edit_person_path(record)}"
          | Linkedin / CV missing
    td
      - if record.primary_tech.present?
        = link_to record.primary_tech, people_path(q: { primary_tech_eq: record.primary_tech })
    td
      div style="background-color: #{PERSON_STATUS_COLORS[record.status]};"
        = link_to (record.status.presence || 'n/a'), people_path(q: {status_eq: record.status}), { style: 'color: black' }
      - if record.start_date.present?
        | Start:&nbsp;
        = record.start_date.strftime(t(:datetime_full)).gsub('00:00, ', '')
        br
      - if record.finish_date.present?
        | Finish:&nbsp;
        = record.finish_date.strftime(t(:datetime_full)).gsub('00:00, ', '')
        br
    td
      - if (record.action_points_count || 0) > 0
        | Upcoming Actions:
        br
        - record.action_points.order(perform_on: :asc).each do |action_point|
          - next if action_point.is_completed
          a href="#{edit_action_point_path(action_point)}" #{action_point.perform_on.strftime(t(:datetime_full)).gsub('00:00, ', '')}
          | &nbsp;
          = with_newlines(action_point.value)
          br

      - if (record.notes_count || 0) > 0
        | Latest notes:
        br
        - record.notes.accessible_by(current_ability).order(updated_at: :desc).each do |note|
          = note.created_at.strftime(t(:day))
          | &nbsp;
          - if !note.type.in?(Note::FINANCE_TYPES) || (note.type.in?(Note::FINANCE_TYPES) && current_user.has_access_to_finances?)
            a href="#{edit_note_path(note)}" #{note.type}
            ' : #{with_newlines(truncate(note.value, length: 300, escape: false))}
          - else
            = "Content of this note is not available (#{note.type})"
          br
      = link_to '+ Note', new_note_path(note: { person_id: record.id })
      br
      = link_to '+ Action', new_action_point_path(action_point: { person_id: record.id })
    td
      - if (record.attachments_count || 0) > 0
        | Attachments:&nbsp;
        br
        - record.attachments.each do |attachment|
          = link_to (attachment.name.present? ? attachment.name : attachment.file_filename), Refile.attachment_url(attachment, :file)
          br
      - if record.city.present?
        ' City:
        = link_to record.city, people_path(q: { city_eq: record.city })
        br
      - if record.linkedin.present?
        a target="_blank" href="#{record.linkedin_value}" LinkedIn
        br
      - if record.github.present?
        a target="_blank" href="#{record.github_value}" Github
        br
      - unless record.tag_list.empty?
        ' Tags:&nbsp;
        - record.tag_list.each do |tag|
          = link_to tag, people_path(q: { by_tag_including: tag })
          | &nbsp;

app/views/people/_table_header.slim
p
  sub #{pluralize(@count, 'result')}

table.table.pretty-table
  thead
    th = sort_link @q, :name
    th = sort_link @q, :primary_tech, 'Tech'
    th = sort_link @q, :status
    th Activity
    th Info
  tbody.js-loadable-list
    = render 'people/table'

app/views/people/edit.slim
h2.title
  | Edit #{@person.name}
  | &nbsp;
  a.btn.btn-default href="#{person_path(@person)}" Back

= render 'form'

app/views/people/new.slim
h2.title New Person

= render 'form_create'

app/views/people/show.slim
.js-edit-form-container style="display:none;"
  h2.title
    | Edit #{@person.name.titleize}
    | &nbsp;
    a.btn.btn-default href="#{person_path(@person)}" Back
  = render 'people/form'

.js-show-container
  - if @person.is_deleted?
    h1
      span style="color: red" DELETED
      br

  h2.title
    = @person.name.titleize
    | &nbsp;
    a.btn.btn-default.js-show-edit-form href="#" Edit
    | &nbsp;
    a.btn.btn-default.js-show-quick-forms href="#" Show Quick Forms
    - if current_user.has_access_to_events?
      | &nbsp;
      a.btn.btn-default href="#{events_path(q: { entity_id_eq: @person.id, action_starts_with: 'person.'})}" Events

  - if @person.status.in?(Person::EMPLOYEE_STATUSES)
    = render 'people/show_employee'
  - else
    = render 'people/show_candidate'

  h3
    | Other &nbsp;
  p
    | Profile created &nbsp;
    = "#{@person.created_at.strftime(t(:datetime_full)).gsub('00:00, ', '')} (#{time_ago_in_words(@person.created_at)} ago)"
  p
    | Profile last updated &nbsp;
    = "#{@person.updated_at.strftime(t(:datetime_full))} (#{time_ago_in_words(@person.updated_at)} ago)"
    | &nbsp; by&nbsp;
    = @person.updated_by&.email&.split('@')&.first

  .js-show-quick-forms-container style="display:none;"
    h3 Quick Forms
    p
      b Add Note
      = render 'notes/form', partial_form: true

    - if !@person.status.in?(Person::EMPLOYEE_STATUSES)
    p
      b Add Action
      = render 'action_points/form', partial_form: true

    - if @person.status.in?(Person::EMPLOYEE_STATUSES)
      p
        b Add Days off
        = render 'dayoffs/form', partial_form: true

      p
        b Add Expense
        = render 'expenses/form', partial_form: true
    p
      b Add Attachment
      = render 'attachments/form', partial_form: true