config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :action_points, except: [:show, :destroy]
  resources :attachments, except: [:show, :destroy]
  resources :dayoffs do
    get :employees, on: :collection
  end
  resources :events, only: :index
  resources :expenses
  resources :notes, except: [:show, :destroy]
  resources :people do
    get :autocomplete_employee_name, on: :collection
    get :autocomplete_person_name, on: :collection
  end
  resources :project_notes, except: [:show, :destroy]
  resources :projects, except: [:destroy] do
    get :autocomplete_project_name, on: :collection
  end
  resources :reports, only: :index do
    collection do
      # get :by_status
      # get :by_technology
      get :current_employees_table
      get :contractors_table
      get :employees_by_birthday_month
      get :employees_by_last_one_on_one_meeting_date
      get :employees_without_performance_review
      get :employees_expenses
      get :employees_history
      get :employees_simple
      get :employees_without_nda_signed
      get :funnel
      get :historical_data
      get :people_with_similar_name
      get :searches
    end
  end
  resources :search, only: :index
  resources :tags, only: :index
  resources :users, except: :destroy
  resources :vacancies, except: :destroy

  root 'home#index'
end

app/views/shared/_form_error.slim
- if object.errors.full_messages.present?
  .text-danger
    | Errors:
    br
    - object.errors.full_messages.each do |error|
      = error
      br

app/views/shared/_load_button.slim
- if collection.limit(nil).offset(nil).size > ENV['ITEMS_PER_PAGE'].to_i && !collection.empty?
  button.btn.btn-success.js-load-more data-limit="#{ENV['ITEMS_PER_PAGE']}"
    span style="display: none;"
    | Load more

app/views/shared/_mail_footer.slim
br
br
span
  | Thank you,
br
span
  | HRMS
br
= link_to ENV['DOMAIN_NAME'], ENV['DOMAIN_NAME']

app/views/shared/_navigation.slim
- if current_user
  .logo
    a href="/"
      | HRMS

  ul.navigation-links
    li.divider
    li.item role="presentation" class="#{active_class('/people') unless active_class(employees_path).present?}"
      a href="#{people_path}"
        i.fa.fa-users
        | &nbsp; People
    li.item role="presentation" class="#{active_class(employees_path)}"
      a href="#{people_path(page: { limit: 10000, offset: 0 }, q: { status_in: Person::EMPLOYEE_STATUSES, sorts: ['status', 'name'] })}"
        i.fa.fa-users
        | &nbsp; Employees
    li.item class="#{active_class('/reports/current_employees_table')}"
      a href="#{current_employees_table_reports_path}"
        i.fa
          | &nbsp;&nbsp;&nbsp; Current
    li.item class="#{active_class('/reports/contractors_table')}"
      a href="#{contractors_table_reports_path}"
        i.fa
          | &nbsp;&nbsp;&nbsp; Contractors
    li.item class="#{active_class('/dayoffs/employees')}"
      a href="#{employees_dayoffs_path}"
        i.fa
          | &nbsp;&nbsp;&nbsp; Days off
    li.item class="#{active_class('/expenses')}"
      a href="#{expenses_path}"
        i.fa
          | &nbsp;&nbsp;&nbsp; Expenses
    li.item role="presentation" class="#{active_class('/vacancies')}"
      a href="#{vacancies_path(q: { status_eq: 'open' })}"
        i.fa.fa-tags
        | &nbsp; Vacancies
    li.item role="presentation" class="#{active_class('/action_points')}"
      a href="#{action_points_path}"
        i.fa.fa-tags
        | &nbsp; Interviews
    li.item role="presentation" class="#{active_class('/tags')}"
      a href="#{tags_path}"
        i.fa.fa-tags
        | &nbsp; Tags
    li.item role="presentation" class="#{active_class('/dayoffs', exclude_str: 'dayoffs/employees')}"
      a href="#{dayoffs_path}"
        i.fa.fa-tags
        | &nbsp; Days off
    li.item role="presentation" class="#{active_class('/projects')}"
      a href="#{projects_path}"
        i.fa.fa-tags
        | &nbsp; Projects
    li.item role="presentation" class="#{active_class('/reports')}"
      a href="/reports"
        i.fa.fa-tags
        | &nbsp; Reports
    li.divider
    - if current_user.has_access_to_users?
      li.item role="presentation" class="#{active_class('/users')}"
        a href="#{users_path}"
          i.fa.fa-users
          | &nbsp; Users
    - if current_user.has_access_to_events?
      li.item role="presentation" class="#{active_class('/events')}"
        a href="#{events_path}"
          i.fa.fa-paw
          | &nbsp; Events