config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :action_points, except: [:show, :destroy]
  resources :attachments, except: [:show, :destroy]
  resources :dayoffs do
    get :employees, on: :collection
  end
  resources :events, only: :index
  resources :expenses
  resources :notes, except: [:show, :destroy]
  resources :people do
    get :autocomplete_employee_name, on: :collection
    get :autocomplete_person_name, on: :collection
  end
  resources :project_notes, except: [:show, :destroy]
  resources :projects, except: [:destroy] do
    get :autocomplete_project_name, on: :collection
  end
  resources :reports, only: :index do
    collection do
      # get :by_status
      # get :by_technology
      get :current_employees_table
      get :contractors_table
      get :employees_by_birthday_month
      get :employees_by_last_one_on_one_meeting_date
      get :employees_without_performance_review
      get :employees_expenses
      get :employees_history
      get :employees_simple
      get :employees_without_nda_signed
      get :funnel
      get :historical_data
      get :people_with_similar_name
      get :searches
    end
  end
  resources :search, only: :index
  resources :tags, only: :index
  resources :users, except: :destroy
  resources :vacancies, except: :destroy

  root 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/views/home/_actions.slim
a.btn.btn-warning href="#{new_person_path}"
  i.fa.fa-user-plus
  | &nbsp;New Person
br

app/views/home/_last_events.slim
h4
  span.label.label-info
    i.fa.fa-line-chart
    |  Latest events

- Event.order(created_at: :desc).limit(20).includes(:user, :entity).each do |record|
  = record.created_at.strftime(t(:datetime_full)).gsub(/\s+/, '&nbsp;').html_safe
  | ,&nbsp;
  = record.user.email.split('@').first
  | ,&nbsp;
  = link_to record.action, events_path('q[action_eq]' => record.action)
  | ,&nbsp;
  - if record.entity.is_a?(Person)
    = link_to record.entity.name.titleize, person_path(record.entity)
  - elsif record.entity.is_a?(User)
    = link_to record.entity.email, users_path
  - elsif record.entity.respond_to?(:person)
    = link_to record.entity.person.name.titleize, person_path(record.entity.person)
  - elsif record.entity.is_a?(Dayoff)
    = link_to "Dayoff##{record.entity_id}", edit_dayoff_path(record.entity)
  - elsif record.entity.is_a?(Vacancy)
    = link_to "Vacancy##{record.entity_id}", edit_vacancy_path(record.entity)
  - else
    = "#{record.entity_type}##{record.entity_id}"
    = ' (Deleted)' if record.entity.blank?
  br

app/views/home/_quick_stats.slim
.cards
  div.card
    .card-title
      a href="/people" People
    .card-body #{Person.not_deleted.count}
  div.card
    .card-title
      a href="/notes" Notes
    .card-body #{Note.count}
  div.card
    .card-title
      a href="/action_points" Actions
    .card-body #{ActionPoint.count}
  div.card
    .card-title
      a href="/attachments" Files
    .card-body #{Attachment.count}
  div.card
    .card-title
      a href="/tags" Tags
    .card-body #{ActsAsTaggableOn::Tag.count}
  div.card
    .card-title
      a href="/vacancies" Vacancies
    .card-body #{Vacancy.count}
  div.card
    .card-title
      a href="/dayoffs" Days off
    .card-body #{Dayoff.count}
  - if current_user.has_access_to_users?
    div.card
      .card-title
        a href="/users" Users
      .card-body #{User.count}
  - if current_user.has_access_to_events?
    div.card
      .card-title
        a href="/events" Events
      .card-body #{Event.count}

app/views/home/_reports.slim
h4
  span.label.label-info
    i.fa.fa-line-chart
    |  Quick Reports

| #{Person.not_deleted.where('created_at > ?', 1.month.ago).count} People added last month
br
| #{Note.where('created_at > ?', 1.month.ago).pluck(:person_id).uniq.count} Unique people contacted last month

app/views/home/_search.slim
form.form action="#{people_path}" method="GET"
  input style="width: 150px" type="text" name="q[name_cont]" placeholder="Name" value=""
  | &nbsp;
  select style="width: 150px" name="q[status_eq]"
    option value="" HR Status
    - PERSON_STATUS_COLORS.each_pair do |status, color|
      - if params.dig(:q, :status_eq) == status
        option selected="selected" value="#{status}" style="background-color: #{color};" #{status}
      - else
        option value="#{status}" style="background-color: #{color};" #{status}
  | &nbsp;
  select style="width: 150px" name="q[primary_tech_eq]"
    option value="" Technology
    - Person::PRIMARY_TECHS.each do |item|
      - if params.dig(:q, :primary_tech_eq) == item
        option selected="selected" value="#{item}" #{item}
      - else
        option value="#{item}" #{item}
  | &nbsp;
  button.btn.btn-default type="submit" Search

app/views/home/index.slim
h2.title
  '  DASHBOARD
  a.btn.btn-small href="#{destroy_user_session_path}" data-method='delete'
    i.fa.fa-sign-out
    |  Sign out
br

= render 'search'
= render 'actions'
= render 'quick_stats'
= render 'reports'
= render 'last_events'

br